### ISSUE TITLE
Map paths to import roots in Rhai.toml

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#80]
Some users may organize their module scripts directly under the source directory, but resolve them into different paths at runtime.

For example, if we have:

```rust
src/
  main.rhai
  modules/
    foo/
      baz/
        main.rhai
    bar/
      main.rhai
```

During runtime, the user may want imports to work this way:

```js
import "baz" as baz;
import "bar" as bar;
```

So can something like this be put into `Rhai.toml`:

```toml
[modules]
foo = "./modules/foo"
bar = "./modules/bar"
baz = "./modules/foo/baz"
```
